$("h1").text('Machine Learning');
Append_('Intro to Machine Learning', ['What is Machine Learning?', 'Where To Start?', 'Data Set', 'Data Types']);
Append_('Mean Median Mode', ['Mean', 'Median', 'Mode']);
Append_('Standard Deviation', ['Standard Deviation', 'Variance', 'Symbols']);
Append_('Percentile', ['Percentiles',]);
Append_('Data Distribution', ['How Can we Get Big Data Sets?', 'Histogram', 'Big Data Distributions', 'Normal Data Distribution']);
Heading("Let's start");
Append_('What is Machine Learning?', ['Machine Learning lifecycle', 'Types of Machine Learning', 'Need for machine learning']);
Append_('Best Python libraries for Machine Learning?', ['Best Python libraries for Machine Learning', 'Difference Between ML and AI', 'General steps to follow in a ML Problem']);
Heading("Data Preprocessing");
Append_('Introduction to Data in Machine Learning', ['How do we split data in ML?',]);
Append_('Understanding Data Processing', ['Understanding Data Processing',]);
Append_('Create Test DataSets using Sklearn', ['Create Test DataSets using Sklearn', 'Benefit of Scikit-learn test datasets']);
Append_('Data Cleaning', ['Data cleaning', 'Steps involved in data cleaning', '']);
Append_('One Hot Encoding', ['One Hot Encoding in ML', 'advantages', 'disadvantages', 'One Hot Encoding Examples', 'Using Pandas library']);
Append_('Dummy variable trap in Regression Models', ['Dummy variable trap in Regression Models',]);
Append_('Exploratory Data Analysis (EDA)', ['Types of EDA', 'Using Python Libraries']);
Append_('Feature Scaling', ['Feature Scaling',]);
Append_('Feature Engineering', ['Why use Feature Scaling?', 'Absolute Maximum Scaling', 'Min-Max Scaling', 'Normalization', 'Standardization', 'Robust Scaling', '']);
Append_('Label Encoding', ['Label Encoding', 'Example of Label Encoding', 'Limitation', 'Example']);
Append_('Handling Imbalanced Data', ['SMOTE - Oversampling', 'NearMiss Algorithm – Undersampling', 'Implement in code']);
Heading("Algorithm");
Append_('What is Algorithm in ML?', ['Algorithm in ML', 'Supervised Learning Algorithms', 'Unsupervised Learning Algorithms', 'Reinforcement Learning Algorithms']);
Append_('Linear Regression', ['What is Linear Regression?', 'Simple Linear Regression', 'What is the best fit line?', 'Gradient Descent', 'Evaluation Metrics', 'Assumptions of Linear Regression', 'Hypothesis in Linear Regression', 'Multiple Linear Regression', 'Multicollinearity', 'Overfitting and Underfitting', 'Bias Variance Tradeoff', 'Coding']);
Append_('Logistics Regression', ['What is Logistic Regression?', 'Types of Logistic Regression', 'How does Logistic Regression work?', 'Logistic Function', 'Cost Function', 'Log Loss', 'Coding', 'Model Evaluation using Confusion Matrix', 'Visualizing Confusion Matrix', 'ROC Curve', 'Advantages of Logistics Regression', 'Disadvantages of Logistics Regression', '']);
Append_('Polynomial Regression', ['Polynomial Regression', 'How Does It Handle Non-Linear Data?', 'Linear Regression Vs. Polynomial Regression', 'Polynomial Regression With One Variable', 'Playing With a Polynomial Degree', 'Polynomial Regression With Multiple columns']);
Append_('K Neareast Neighbour (KNN)', ['Intuition Behind KNN Algorithm', 'Distance Metrics Used in KNN Algorithm', 'How to choose the value of k', 'Workings of KNN', 'Applications of the KNN', 'Advantages & Disadvantages', 'Implementation using sklearn']);
Append_('Decision Tree', ['Decision Tree Terminologies', 'Example of Decision Tree', 'Decision Tree Assumptions', 'Entropy', 'Information Gain', 'When to Stop Splitting?', 'Pruning', 'Code Implementation']);