$("h1").text('NumPy');
Heading("Intro");
Append_('Numpy - Quickstart', []);
Append_('Numpy - Introduction', []);
Append_('Numpy - Environment', []);
Append_('Ndarray Object', []);
Append_('Data Types', []);
Append_('Array Attributes', []);
Append_('Array Creation Routines', []);
Append_('Array From Existing Data', []);
Append_('Array From Numerical Ranges', []);