$("h1").text('Python');
Heading('Intro');
Append_('Intro to Python', ['About Python', 'Python Syntax', 'Python Indentation', 'Comments']);
Heading('Variables & Data types');
Append_('Variables', ['Variables']);
Append_('Data Types', ['Python Data Types', 'Most Used Data Types', 'Getting the Data types']);
Append_('Numbers', ['Python Numbers', 'int', 'float', 'complex', 'Type Conversion']);
Append_('String', ['Python Strings', 'Multiline Strings', 'Strings are arrays', 'String Length', 'Slicing', 'Slice from the start', 'Slice to the end', 'Negative Indexing', 'Modify Strings', 'String Format', 'Escape Character']);
Append_('Booleans', ['Most Values are True', 'Some Values are False']);
Append_('Lists', ['List items', 'List Length', 'List Items - Data types', 'Data type of List', 'Python Collections(Arrays)', 'Access Items', 'Change Item Value', 'Change List items', 'Insert Items', 'Add List Items', 'Remove List Items', 'Sort Lists', 'Copy Lists', 'Join Lists', 'List Methods']);
Append_('Tuples', ['Tuple Items', 'Tuple Length', 'Tuple Items - Data Types', 'Access Tuple Items', 'Update Tuples', 'Add Items', 'Remove Items', 'Unpack Tuples', 'Join Tuples', 'Tuple Methods']);
Append_('Sets', ['Set Items', 'Length', 'Set Items - Data Types', 'type()', 'Access Set Items', 'Change Items', 'Add Items', 'Add Sets', 'Add Any Iterable', 'Remove Set Items', 'Join Sets', 'Set Methods']);
Append_('Dictionaries', ['Dictionary Items', 'Ordered or Unordered?', 'Changeable', 'Duplicates Not Allowed', 'Length', 'Dictionary Items - Data Types', 'type()', 'dict() Constructor', 'Access Dictionary Items', 'Get Keys', 'Get Values', 'Get Items', 'Check if Key Exists', 'Change Values', 'Update Dictionary', 'Add Dictionary Items', 'Remove Dictionary Items', 'Copy a Dictionary', 'Nested Dictionaries', 'Dictionary Methods']);
Heading('Operators');
Append_('Operators', ['Basic Operator', 'All operators']);
Heading('Conditional Statement');
Append_('If...Else', ['Indentation', 'If ... Else', 'Elif', 'Else', 'Short Hand If', 'Short Hand If ... Else', 'And', 'Or', 'Not', 'Nested If', 'The pass Statement']);
Heading('Loops');
Append_('While Loop', ['break', 'continue', 'else Statement']);
Append_('For Loop', ['Looping Through a String', 'break', 'continue', 'range() Function', 'Else in For Loop', 'Nested Loops', 'pass Statement']);
Heading('Functions');
Append_('Function', ['Creating a Function', 'Calling a Function', 'Arguments', 'Parameters or Arguments?', 'Number of Arguments', 'Arbitrary Arguments, *args', 'Keyword Arguments', 'Arbitrary Keyword Arguments, **kwargs', 'Default Parameter Value', 'Passing a List as an Argument', 'Return Values', 'pass Statement', 'Recursion']);
Append_('Lambda', ['Why Use Lambda Functions?']);